/*
SQLyog Professional
MySQL - 10.4.20-MariaDB : Database - BASE
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `USER` */

CREATE TABLE `USER` (
  `USER_ID` int(50) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(50) DEFAULT NULL,
  `MIDDLE_NAME` varchar(50) DEFAULT NULL,
  `LAST_NAME` varchar(50) DEFAULT NULL,
  `AGE` int DEFAULT NULL,
  `PHONE_NUMBER` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `BIRTHDAY` date DEFAULT NULL,
  `STATUS` char(1) DEFAULT 'A',
  `UPDATE_DATE` datetime DEFAULT current_timestamp(),
  `CREATE_DATE` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ADDRESS` (
  `ADDRESS_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(50) NOT NULL,
  `HOUSE_NO` VARCHAR(50) DEFAULT NULL,
  `BARANGAY` VARCHAR(100) DEFAULT NULL,
  `CITY` VARCHAR(100) DEFAULT NULL,
  `PROVINCE` VARCHAR(100) DEFAULT NULL,
  `ZIP` VARCHAR(10) DEFAULT NULL,
  `UPDATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP(),
  `CREATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`ADDRESS_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`) ON DELETE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `OTP` (
  `OTP_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(50) NOT NULL,
  `VALUE` VARCHAR(50) NOT NULL,
  `STATUS` VARCHAR(50) NOT NULL,
  `CREATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`OTP_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SESSION` (
  `SESSION_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(50) NOT NULL,
  `LOGIN_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP(),
  `STATUS` CHAR(1) DEFAULT 'A',
  PRIMARY KEY (`SESSION_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LOGIN_ATTEMPT` (
  `ATTEMPT_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` int(50) NOT NULL,
  `ATTEMPT_DATE` datetime DEFAULT current_timestamp(),
  `SUCCESS` boolean DEFAULT false,
  PRIMARY KEY (`ATTEMPT_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- CUSTOMER ---

CREATE TABLE `CUSTOMER` (
  `CUSTOMER_ID` int(50) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(50) DEFAULT NULL,
  `MIDDLE_NAME` varchar(50) DEFAULT NULL,
  `LAST_NAME` varchar(50) DEFAULT NULL,
  `AGE` int DEFAULT NULL,
  `PHONE_NUMBER` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `BIRTHDAY` date DEFAULT NULL,
  `STATUS` char(1) DEFAULT 'A',
  `UPDATE_DATE` datetime DEFAULT current_timestamp(),
  `CREATE_DATE` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ADDRESS_CUSTOMER` (
  `ADDRESS_ID` INT(50) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT(50) NOT NULL,
  `HOUSE_NO` VARCHAR(50) DEFAULT NULL,
  `BARANGAY` VARCHAR(100) DEFAULT NULL,
  `CITY` VARCHAR(100) DEFAULT NULL,
  `PROVINCE` VARCHAR(100) DEFAULT NULL,
  `ZIP` VARCHAR(10) DEFAULT NULL,
  `UPDATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP(),
  `CREATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`ADDRESS_ID`),
  FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`) ON DELETE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SESSION_CUSTOMER` (
  `SESSION_ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT(50) NOT NULL,
  `LOGIN_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP(),
  `STATUS` CHAR(1) DEFAULT 'A',
  PRIMARY KEY (`SESSION_ID`),
  FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LOGIN_ATTEMPT_CUSTOMER` (
  `ATTEMPT_ID` int NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int(50) NOT NULL,
  `ATTEMPT_DATE` datetime DEFAULT current_timestamp(),
  `SUCCESS` boolean DEFAULT false,
  PRIMARY KEY (`ATTEMPT_ID`),
  FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
